// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// For Prisma 5+, use the default config approach
export default {
  schema: "prisma/schema.prisma",
  output: "../src/generated/prisma",
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
};
